### ISSUE TITLE
S11.3 - Add success/error messages to query runs / saves

### ISSUE THREAD

**Issue by RamiAwar** [RamiAwar/dataline#130]
Create success / error messages for when we run SQL queries or save edited ones.

I tried doing it myself but got weird issues like getting multiple messages on run, and also getting these messages when I save a query! Not sure why, very curious to know.
![Image](https://github.com/RamiAwar/dataline/assets/8523191/246e40a8-745b-4d2a-9e30-0f7cf837f7fd)

**Comment by anthony2261** [comment]
For the success message, are we sure we want to use the snackbar instead of a tooltip message that pops over the button that was clicked?
The error message would be a snackbar since it's potentially a longer message

**Comment by RamiAwar** [comment]
Yeah let's just use a snackbar, it's more visible. We'll just set it to something that disappears quickly. I don't wanna build a tooltip and make sure it 's visible and and and. Snackbar is quick and dirty but also great UX.

**Comment by anthony2261** [comment]
Done in #129, will automatically close on merge
