### ISSUE TITLE
S13.1 - Fix data linking issue

### ISSUE THREAD

**Issue by anthony2261** [RamiAwar/dataline#156]
Selected tables results are not easy to link to sql results:
- Some messages naturally don't include a generated SQL result, like explorative messages. However, the LLM might still choose to use the InfoSQLDatabaseTool
- If the user requests multiple things in a single message, the openAI tool call might call the InfoSQLDatabaseTool more than once in a single shot (good for parallelization). It then becomes hard to know which call to the InfoSQLDatabaseTool corresponds to which generated sql

**Comment by anthony2261** [comment]
Reopening as the temporary fix only addresses a small part of the issue

**Comment by RamiAwar** [comment]
What remains of this issue? @anthony2261

**Comment by anthony2261** [comment]
> If the user requests multiple things in a single message, the openAI tool call might call the InfoSQLDatabaseTool more than once in a single shot (good for parallelization). It then becomes hard to know which call to the InfoSQLDatabaseTool corresponds to which generated sql

@RamiAwar This one isn't addressed yet. Some selected tables results might even be linked to the wrong generated sql results

**Comment by anthony2261** [comment]
One idea I had was to combine all the selected tables results together, and place the aggregated result at the top just below the message content. But I'd like to explore other solutions as well

**Comment by RamiAwar** [comment]
Makes sense. I like just grouping selected results and being done with it. I get many results where I have 3+ selected tables results and it just looks super weird.

Any updates on other solutions? I say we just throw them together for now.
