### ISSUE TITLE
AI generates SQL as text instead of using the tool

### ISSUE THREAD

**Issue by anthony2261** [RamiAwar/dataline#170]
Sometimes the AI responds with SQL in the message text, instead of calling the QuerySQLDataBaseTool.

![image](https://github.com/RamiAwar/dataline/assets/26882839/0794df45-ca13-42c1-846f-ae134de01c7e)

I suspect part of the reason is because of the way we gather the message history that's passed into the AI

![image](https://github.com/RamiAwar/dataline/assets/26882839/c0eea918-8d6e-46ed-9137-e97f535a171f)
![image](https://github.com/RamiAwar/dataline/assets/26882839/a20232e2-6fb8-4f70-9f0f-f7d1b09275c0)

**Comment by RamiAwar** [comment]
I think function message is the equivalent of tool message when you use function calling. It might be rejected if you don't call a function.

But then even if it's not, don't lovee the solution.

Gonna try and think of other ways to solve this

**Comment by RamiAwar** [comment]
Is this fixed? @anthony2261

**Comment by anthony2261** [comment]
No, wanna pick it up? It usually happens in chats with long histories,
maybe like 10 messages +

**Comment by RamiAwar** [comment]
Nah forget it for now. We'll add a test for it or something
