### ISSUE TITLE
Add a model picker

### ISSUE THREAD

**Issue by anthony2261** [RamiAwar/dataline#171]
Allow users to pick the AI model they would like to use. We already have a "preferred model" field on the user settings in the backend, we need add a way to change it on the frontend. We should also use the current openai key to see which models the user has access to

**Comment by RamiAwar** [comment]
Blocked until we have a testing pipeline - do not want to expose all models as some perform badly, that would reflect badly on DataLine, we should expose models carefully after they pass our upcoming regression test.
