### ISSUE TITLE
Docker build locks database

### ISSUE THREAD

**Issue by RamiAwar** [RamiAwar/dataline#190]
Whenever running the app in docker, the database seems to get locked automatically after running a first query. 
Even the first message is not saved, indicating that the lock happened from the beginning.

To replicate:

Clean DB
Upload CSV file
Perform query in a new chat
* failed due to lock *

IN addition, all sample DBs fail to initialize.

**Comment by RamiAwar** [comment]
Volume looks like it's empty from the start, suggesting that the mount is faulty.

It should at least contain the sample DBs.

**Comment by RamiAwar** [comment]
Partial fix for DB samples added. 

I have a hypothesis that the DB is not getting stored where it should be, on the volume. Might be env var related, we haven't tested docker properly since we added the user data configs.

**Comment by RamiAwar** [comment]
Can confirm DB is being created successfully in the docker volume. Just not visible in docker desktop.

To access the docker volume path seen in `docker volume inspect dataline` we need to use this:

`docker run -it --rm --privileged --pid=host alpine:edge nsenter -t 1 -m -u -n -i sh` to get into the main VM docker uses. Then the path is accessible.

<img width="695" alt="image" src="https://github.com/RamiAwar/dataline/assets/8523191/da8a7f5f-9501-4912-9a79-1da408273407">

This narrows it down a bit. Seems to be something accessing the DB and not closing the connection properly, and this ONLY happens when dockerized.

**Comment by anthony2261** [comment]
Fixed due to fastapi breaking change
