### ISSUE TITLE
OpenAI responses include unknown multi tool parallel call

### ISSUE THREAD

**Issue by RamiAwar** [RamiAwar/dataline#214]
Known issue, we just need to patch it:
https://community.openai.com/t/model-tries-to-call-unknown-function-multi-tool-use-parallel/490653

Open source patches don't support async streaming. Been trying to catch it again for a while but not managing to. Added a breakpoint here but never managed to trigger it. Ignore the actual line, just dummy code. I just want to look into the returned json.

<img width="893" alt="image" src="https://github.com/RamiAwar/dataline/assets/8523191/0ef101f0-65a4-4b65-a352-bbead0c24d88">

**Comment by RamiAwar** [comment]
Caught one! Just need to patch it now.
![image](https://github.com/RamiAwar/dataline/assets/8523191/2e2cbb3c-0dea-46ea-be8d-8b12e52b92dd)

**Comment by RamiAwar** [comment]
What it should look like:
<img width="511" alt="image" src="https://github.com/RamiAwar/dataline/assets/8523191/aa77f97c-be5e-4882-82fa-58a7b1930059">

**Comment by anthony2261** [comment]
I think this was fixed in #277
