### ISSUE TITLE
Update snowflake-sqlalchemy 2.0 upon release

### ISSUE THREAD

**Issue by RamiAwar** [RamiAwar/dataline#217]
Right now we're using pip to install snowflake-sqlalchemy 2.0 from a branch.

When 2.0 support is officially released, we should update the Dockerfile and README and just install it with poetry and lock it.

**Comment by anthony2261** [comment]
Update: we've added it to pyproject.toml, it is now downloadable via poetry (https://github.com/RamiAwar/dataline/pull/219). But it's still through a branch, not the officially released package

**Comment by anthony2261** [comment]
Closed via #219

**Comment by RamiAwar** [comment]
> Update: we've added it to pyproject.toml, it is now downloadable via poetry (#219). But it's still through a branch, not the officially released package

Yess I realize, just wanna leave this open so we don't forget about it. 😬
