### ISSUE TITLE
"Install" section on landing page not well shown

### ISSUE THREAD

**Issue by anthony2261** [RamiAwar/dataline#225]
The right part is quite small
![image](https://github.com/RamiAwar/dataline/assets/26882839/509c3071-1297-4368-b25e-1fc6a46305fc)

**Comment by RamiAwar** [comment]
Woah what screen size is this?

**Comment by rohitt-gupta** [comment]
nto able to reproduce?

**Comment by RamiAwar** [comment]
mightve been fixed then, let's close this 🙂

**Comment by anthony2261** [comment]
Yep, looks a bit better now, I'm using a widescreen btw
