### ISSUE TITLE
Setting data security on after turning it off doesn't actually set it on again

### ISSUE THREAD

**Issue by anthony2261** [RamiAwar/dataline#226]
Picture below shows "Data secure" icon but the response actually contains info from the table

![image](https://github.com/RamiAwar/dataline/assets/26882839/2cf062e9-62e1-4929-aef2-795dac9cb44b)

**Comment by anthony2261** [comment]
OK, false alarm, I checked the langsmith logs, it is actually secure. This is a question that people wrote about on the internet using this sample db, so the LLM probably memorized the result. We can also see that the LLM says 231.57 while the table says 231.73

**Comment by RamiAwar** [comment]
Yes I've seen similar results before, specially with other models like 4o
