### ISSUE TITLE
Fix React 404 Not Found page

### ISSUE THREAD

**Issue by RamiAwar** [RamiAwar/dataline#231]
- [ ] Add a custom not found page (when auth is disabled)
- [ ] Redirect to auth (when auth is enabled)

**Comment by Nirajan1-droid** [comment]
could you please assign me this issue :)

**Comment by RamiAwar** [comment]
Yes sure! 😊

**Comment by RamiAwar** [comment]
You will see this when you navigate to a router page that doesnt exist

**Comment by RamiAwar** [comment]
Fixed with move to tanstack router

**Comment by Nirajan1-droid** [comment]
@RamiAwar i am sorry for being late. 
i am little sick now.

**Comment by RamiAwar** [comment]
Oh don't worry about it hahaha @Nirajan1-droid 

@anthony2261 closed this without realizing as part of his other work, we weren't really in a rush! It could still use some polish if you'd like to work on it! We just shipped a very basic 404 page

**Comment by Nirajan1-droid** [comment]
ok @RamiAwar thank you for your kind response. 
i will look into other issues :)

**Comment by anthony2261** [comment]
Hey @Nirajan1-droid I only added the template 404 response from the tanstack router package, and as you can see it doesn't look great

![image](https://github.com/user-attachments/assets/dd71643a-343c-4506-bb5b-441a7c16845a)

You can see the code for it in `frontend/src/routes/__root.tsx`, if you feel like making it look nicer then please do! 😄

**Comment by Nirajan1-droid** [comment]
sure 😃
