### ISSUE TITLE
markdown support

### ISSUE THREAD

**Issue by vasnt** [RamiAwar/dataline#239]
Possible to add support for markdown files? so i can query easily obsidian/other notes?

sample query:

- List down all bulleted points/sentences that has tag #xyz and backlink [[abc]]

**Comment by RamiAwar** [comment]
Hey Vasnt! That seems like an interesting usecase honestly.

My first thought is creating a markdown -> SQLite script and then you just plug it in. But it wouldn't be an exactly live connection. We could still 'refresh' it every once in a while but not really live.

I'd say this isn't exactly DataLine territory, but depending on how you want to do it it could be.

**Comment by vasnt** [comment]
- refreshing once in a while should not be a big issue.
- i am not much technical, so i can just agree whatever you said : markdown -> SQLite script 

other use-cases:
- i would like to get structured outputs from unstructured data(usually markdown files are text/sentence based, so i call it unstructured)
e.g. if i ask to fetch data from markdown notes like: license no, exam scores, last year's expenses etc.  & tabulate them.

**Comment by RamiAwar** [comment]
Okay I see, yeah that's not really what DataLine is built for - that's more of a vector embedding DB search, lots of tools already do this!

We focus more on querying structured data in a more complex way and building charts and exporting tables and stuff. More data analysis stuff than "answer a general question based on unstructured data" if you know what I mean.
