### ISSUE TITLE
Support for Generic OpenAI endpoints

### ISSUE THREAD

**Issue by emerzon** [RamiAwar/dataline#240]
Please add to the config the ability to set the `base_url` param for the  OpenAI.

This will allow the usage of Generic OpenAI endpoints (Azure OpenAI, LiteLLM, etc)

**Comment by RamiAwar** [comment]
Thanks for submitting this @emerzon ! This should be easy to achieve.

**Comment by zhaoxin-jia-tfs** [comment]
is there any plan to support this base_url?

**Comment by RamiAwar** [comment]
Yupp, we've got our hands full with a few things at the moment but we'll pick this up in a week or two max.

**Comment by anthony2261** [comment]
Hey @emerzon thanks for you patience on this one! The feature branch has been merged and will be included in the next release 🥳
