### ISSUE TITLE
ERROR:main:BaseGPTIndex.__init__() got an unexpected keyword argument 'documents'

### ISSUE THREAD

**Issue by Diaznano** [RamiAwar/dataline#27]
hello
i'm trying to test the project, but when i connect to my mysql or postgres database, i get this error

![code](https://user-images.githubusercontent.com/12193387/236487362-ba5f71da-6eca-434f-a07c-f46a4f539a66.png)

this line is where the problem lies as far as I have investigated
`table_schema_index = context_builder.derive_index_from_context(GPTSimpleVectorIndex)`

Reading in forums and researching, I did not find the solution to this problem, do you have any idea why it could be or how to solve it?

@RamiAwar

**Comment by RamiAwar** [comment]
Hey! Could you provide more details on how you're running it? The docs can definitely be improved, so I'll help you through this and incorporate your feedback 😃

**Comment by Diaznano** [comment]
Hi! thanks for your response

Follow the steps you left in the readme. The only difference is that it connects to a mysql database, here is the string
mysql://root:****@localhost:3306/dbExample

<img width="908" alt="Captura de pantalla 2023-05-05 a la(s) 20 21 56" src="https://user-images.githubusercontent.com/12193387/236584098-a32f39d1-ec8a-4462-abbc-08de8cde1930.png">
<img width="1139" alt="Captura de pantalla 2023-05-05 a la(s) 20 23 27" src="https://user-images.githubusercontent.com/12193387/236584100-8125e7b3-5898-44e5-ba3a-32c00ede4275.png">

**Comment by RamiAwar** [comment]
Trying to replicate the issue by running a mysql container locally. I only ever tried this project with postgres. Will keep you updated here.

**Comment by RamiAwar** [comment]
Okay so I encountered a few issues while trying to connect to mysql, this is what worked for me:

- First I installed mysql with brew and ran it as a service (could also be a docker container)
- Then I added the dependency PyMySQL to the project (a pure python connector, only one that I managed to install successfully)
- Next I connected with the following connection string, notice the connector part: `mysql+pymysql://root:secret@localhost:3306/mydatabase`

I didn't manage to replicate the error, the connection worked directly for me and I managed to query some dummy data successfully.

Try adding `+pymysql` to your connection string and let me know if this still happens! @Diaznano
