### ISSUE TITLE
backend deployment failed

### ISSUE THREAD

**Issue by jerry0li** [RamiAwar/dataline#289]
### Privileged issue

- [X] I'm @ramiawar or he asked me directly to create an issue here.

### Issue Content

Followed by the steps in `backend/README.md` shown below without success. 
```
poetry env use python3.11
poetry config virtualenvs.in-project true
poetry install --no-root

SQLITE_PATH="." # Define where sqlite DB will be stored

poetry shell # Active python environment (makes alembic command available)
alembic upgrade head # Run migrations
```

The error msg:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

Could you help me solve this error? Thanks a lot.

**Comment by anthony2261** [comment]
Hey @jerry0li, I think this is indeed an error in the backend's README file, but it's an easy fix:
You can run the alembic command by prepending the SQLITE_PATH variable to it, like so: `SQLITE_PATH="./db.sqlite3" alembic upgrade head`

If you do it this way, make sure every time you run the dataline backend server, you also add this variable, i.e. `SQLITE_PATH="./db.sqlite3" uvicorn dataline.main:app --reload --port=7377`

Let me know if this solves it for you!
