### ISSUE TITLE
S5.6 - Add option for deleting connections

### ISSUE THREAD

**Issue by RamiAwar** [RamiAwar/dataline#86]
- Cascade delete on schema fields, tables (I think those are the only tables referencing connections?)
- Frontend button to delete from the connection editor (above the schema descriptions cause that list might be long AF)
- Backend route

**Comment by anthony2261** [comment]
Deleting a connection would affect almost all the tables, namely:
- Schema Table -- FK to connection
  - Schema Field -- FK to schema table
- Conversation -- FK to connection
  - Conversation Message -- FK to Conversation
    - Message would be dangling since there would be no Conversation Message to link it to the (now deleted) conversation
    - Message Result dangling as the related message would be dangling
    - Result -- related to messages
      - Saved Query related to Result

So... what do you suggest we do?
